# -*- mode: ruby -*-
# vi: set ft=ruby :

# Esta es la configuración minima para vagrant v2, para un ambiente multimáquina
Vagrant.configure("2") do |config|

  config.vm.provider "hyperv" do |vb|
    # Rerserv de Memoria para cada instancia
    vb.memory = "512"
    vb.vm_integration_services = {
      guest_service_interface: true,
     CustomVMSRV: true
    }
  end

 config.vm.define "instancia1" do |in1|

   in1.vm.box = "wangkexiong/ubuntu-focal"
 end

end
